# Generated by Django 4.2.25 on 2025-10-12 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('can_view_events', 'Can view events'), ('can_register_event', 'Can register for events'), ('can_create_event', 'Can create events'), ('can_edit_event', 'Can edit events'), ('can_delete_event', 'Can delete events'), ('can_approve_organizer', 'Can approve organizers')]},
        ),
    ]
