# Generated by Django 4.2.25 on 2025-10-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
