# Generated by Django 5.2.7 on 2025-11-03 02:21

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('main', '0003_alter_event_options'),
#     ]

#     operations = [
#     ]


from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for name in ['Administrator', 'Organizer', 'Student']:
        Group.objects.get_or_create(name=name)

class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_alter_event_options'),
    ]
    operations = [
        migrations.RunPython(create_groups),
    ]
