# Generated by Django 4.2.25 on 2025-10-13 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_event_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=64, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to=main.models.models.qrcode_upload_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='main_ticket_code_c31f0f_idx')],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
