# Generated by Django 4.2.25 on 2025-10-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ticket_alter_event_attendees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='purchased_at',
            new_name='purchase_date',
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('event', 'user')},
        ),
    ]
