# Generated by Django 4.2.25 on 2025-10-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_savedevent_event_payment'),
        ('main', '0005_rename_purchased_at_ticket_purchase_date_and_more'),
    ]

    operations = [
    ]
