# Generated by Django 4.2.16 on 2025-11-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    # FIX: depend on the real previous migration we have locally
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="first_scanned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="last_scanned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="qr_token",
            field=models.CharField(
                max_length=64, unique=True, null=True, blank=True, db_index=True
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="scan_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
